### ISSUE TITLE
Confused about `AEAD Checksum` in retry token

### ISSUE THREAD

**Issue by william-zk** [quicwg/load-balancers#108]
Hi martin:

1. It seems that draft limits the encryption algorithm of retry token must be `AES-128-GCM`, but the description of AEAD CheckSum is `AEAD Checksum (length depends on encryption algorithm)`.

2. Further more, what is `AEAD Checksum` and why we need it? AEAD encryption algorithm just need `key, association data , iv` to do encryption/decryption and authentication.

**Comment by martinduke** [comment]
Hi William

1) The checksum thing is a good point. I'll fix it.

2) Like for QUIC packets themselves, there is an authentication tag that AES-GCM generates and we append it to the token. I am not a crypto expert, but I believe this is how the decoder detects if the AAD was changed or there's a problem with the ciphertext.

**Comment by william-zk** [comment]
> 2\. Like for QUIC packets themselves, there is an authentication tag that AES-GCM generates and we append it to the token. I am not a crypto expert, but I believe this is how the decoder detects if the AAD was changed or there's a problem with the ciphertext.

You means that `checksum ` is something just like `Retry Integrity Tag` in `Retry packet`? If so, I think it's a redundant design,  the design of `Retry packet` can ensure that the data can not be tampered with. Moreover, if we must need this, maybe we should have an alternative name of `checksum`, and give a more detail description of it
