### ISSUE TITLE
Align stream cipher and block cipher formats

### ISSUE THREAD

**Issue by huitema** [quicwg/load-balancers#121]
The clear text stream cipher and block cipher formats are specified as:
```
[B][nonce][server-ID][server-use]
[B][server-ID][server-use]
```
I think that this difference is not necessary. In the block cipher format, the first `16-length_of_sid` bytes are effectively used as a nonce: using the same value and the same server ID would result in the same initial 16 bytes, with exactly the same privacy effect as failing to properly initialize the nonce in the stream-cipher case. I wish we could unify these two formats, to:
```
[B][server-ID][server-use]
```
With just three parameters:
```
[B][     server-ID      ][     server-use     ]
   <-- length of SID -->
   <--- scope of encryption --->
<--------------- length of CID --------------->
```
The scope of encryption would be 0 bytes for the clear text format, 16 bytes for the block cipher format, and a value greater than server-ID length and lower than the length of the CID for the stream cipher format. This will of course require that the first bytes of the server-use field act as a nonce. Alternately, we could have:
```
[B][     server-ID      ][ nonce ][ server-use  ]
   <-- length of SID -->
   <---- scope of encryption ---->
<---------------- length of CID ---------------->
```
Which achieves the same unification result, but is maybe a bit more explicit.

**Comment by martinduke** [comment]
I think this would simplify things, yes. Though it might be worth it to separate the server-use bit into a nonce and server-use, since one has uniqueness constraints and one doesn't.

**Comment by martinduke** [comment]
I like how this is developing.

I should clarify that the "CID length" is actually the minimum length of the CID -- that's all the LB will look at. The server can pad it out to 20B but that's not relevant to the algorithm.

Regarding the first byte: if using length-self-encoding, there will be little or not entropy there.

I don't think the case for a 16B SID is compelling.
