### ISSUE TITLE
"appear to be random"

### ISSUE THREAD

**Issue by martinthomson** [quicwg/load-balancers#192]
https://xkcd.com/221/ is probably not your intent, but that is what you get with this phrasing.  I think that the point is that the values are not predictable to entities other than the one generating it.  This appears in several places in the document.

**Comment by martinduke** [comment]
Well https://www.rfc-editor.org/rfc/rfc9000.html#name-stateless-reset uses "indistinguishable from random" :-)

But OK, I'll seek a new formulation.
