### ISSUE TITLE
Extra bytes

### ISSUE THREAD

**Issue by martinthomson** [quicwg/load-balancers#194]
> The server MAY append additional bytes to the connection ID, up to the limit specified in that version of QUIC, for its own use. 

This is not particularly clear.  If there is an encoded length, presumably this needs to fit within that.  Or does it?  I believe that as long as the length identifies the portion of the connection ID that the load balancer needs to look at (i.e., the server ID or the encrypted part that contains the server ID) the connection ID could be longer than the indicated length and this would still work.

> These bytes MUST NOT provide observers with any information that could link two connection IDs to the same connection, client, or server. In particular, all servers using a configuration MUST consistently add the same length to each connection ID, to preserve the linkability objectives of QUIC-LB. 

I think that the reason you add the same length is because RFC 9000 requires it.  It does that because otherwise it would be impossible to know where the connection ID ends for a short header because it lacks a length field.  It has nothing to do with linkability.

**Comment by martinduke** [comment]
If the LB is configured to look at, for example, the first 17 bytes of a connection ID, it really doesn't matter if the server chooses to use 17, 18, 19, or 20 byte connection IDs. As you say, in a short header the LB can't even discern that the later bytes are part of the connection ID.

I don't see any point in RFC 9000 the prohibits a server sometimes issuing 17B CIDs on some connections and 18B connection IDs on some other ones. The only problem is if this differs by backend server, in which case it serves as a linkability vector.

Maybe this is unclear and can be reworded?

**Comment by martinduke** [comment]
Closing, assuming this response was satisfactory?
