### ISSUE TITLE
Load Balancing Invariant Longer Header Packets

### ISSUE THREAD

**Issue by nibanks** [quicwg/load-balancers#20]
We've had some discussion in this area in the past, and we decided that the best way to statelessly (and consistently) load balance long header packets would be to use a hash of the UDP 4-tuple and the client's source CID; since these are the only constants for all incoming (to the server) long header packets. I have come up with a couple of problems with this approach:

1. As far as I know, there is no statement in the Invariants that says these must all stay constant for all future versions of QUIC.

2. Using the hash approach can only function statelessly if there is not change in the DIP configuration. If the set of servers being load balanced changes (which we must assume to be common), then whatever stateless logic you have that maps hash to DIP would also change, resulting in long header packets getting routed incorrectly most likely.

3. A follow up to (2), if you assume that the long header packets cannot therefore be routed statelessly based on the hash, and state must be tracked to continue to consistently route all long header packets until they are no longer used, at what point can the LB discard this state. By design, there is no on-path signal to indicate "long header packets are no longer used". Any heuristic that might be added here would be affected by (1) too.

Because of these issues, I'm left scratching my head on the best way to recommend to LBs on how to load balance invariant long header packets. The best thing I can think of is:

- Use the hash mentioned above, but maintain state for each flow (tuple+client_cid).
- Reset a timer (5 sec? 10 sec? 30 sec?) after each new packet is received for the flow. Discard the state when the timer fires.

Because the client's CID is included in the flow calculation, it allows an attacker to create nearly unlimited number of flow states on the LB. You might argue that Retry could be first used by a (cooperating) DoS appliance to first validate source address, but after that is done, this attack can still be executed. It would then require some heuristics on the LB to protect against.

@martinduke @martinthomson any ideas here?

**Comment by nibanks** [comment]
Another, simpler option is just to say live with the disruption of doing things statelessly. Only connections in the second round trip of the handshake would be affected (depending on loss). It's a fairly small window of time, compared to the lifetime of connections. But the clients that do get dropped have a really bad experience, because there will be no stateless reset to immediately kill their connection. They'd have to wait for a timeout.

**Comment by udippant** [comment]
Re (2) - that problem exists for TCP as well. I.e. if you route an incoming TCP connection from a  stateless L4LB to backend servers based on 4-tuple hash, any change in number of backend servers can result in the routing of subsequent packets for the same flow to a different backend server.

Using LRU cache for such connection table in L4LB has been a convenient way to address this issue for us ( for >99% of the flows). You may need to tune parameters such as size and TTL for items in the table to your needs. 
Also, a pre-configured upper bound to limit the size of the connection table should address the concern you mentioned regarding exposure to attack vector of unlimited states in L4LB. 

Finally, even for LongHeader packets, packets of type 'Handshake' echo back the "destination connection id' chosen by the server. So you can use similar logic to route these LongHeader sub-types as you use to route ShortHeader packets if the servers and L4Lb cooperatively choose the 'destination connection Id' [for e.g. as @martinduke  proposed].

**Comment by nibanks** [comment]
Yeah, a LRU cache is a good solution. The difference between TCP and QUIC here is that TCP provides on path signals the LB can use to clean up state, but QUIC doesn't provide any. So, it' is purely a LRU + some timer.

Also, I'm looking for an invariant solution to routing packets. The fact that Handshake packets are similar to Short header packets assumes too much about the per-version semantics.

**Comment by martinduke** [comment]
The draft already addresses this issue in Section 4.

Except for some Initial and 0RTT packets, all DCIDs are server generated and so there is no routing problem.

For Initial/0RTT, the DCID might turn out to be routable (e.g. it came from a Retry). If not, it is a "non-compliant DCID" which is dropped if it's in a short header. If it's a long header:

> Load balancers MUST forward packets with long headers with non-compliant DCIDs to an active server using an algorithm of its own choosing. It need not coordinate this algorithm with the servers. The algorithm SHOULD be deterministic over short time scales so that related packets go to the same server.

This approach is designed to be version-invariant. I suppose a later version could drastically lengthen the time that non-server-generated CIDs were used, but I don't see why they would. The time scale till we get a server-generated CID is quite small, and if somehow the hash still messes up, the only affect is that 0RTT packets get sprayed where they aren't useful. I'm not too worried about that. Ultimately, if neither CID nor UDP tuple is stable, I don't know how you even map the packet to a connection independently of the load balancer problem.

**Comment by nibanks** [comment]
If we want a version-invariant solution (which is my immediate goal), we can't special case any of the long header packets based on type (Initial, Handshake, 0-RTT).

But, either way, @martinduke it sounds like you're in the boat of "do it stateless and live with the (hopefully small) consequences"?

**Comment by martinduke** [comment]
Yes, I am on team stateless.

We don't need to process the packet subtype (Initial, Handshake, 0RTT). The QUIC-LB language just talks about long headers. There are some embedded assumptions: specifically, that client-generated DCIDs aren't around for a long time, and are only in long headers.

I do think you're raised a point that we should explicity express our assumptions about version invariance. There are a few pathological things future versions could to to make the CID encoding fail: extremely small max CID lengths, client-generated CIDs in short headers, very long intervals before switching to server-generated CIDs, etc.

Moreover, the LB requirement to use some algorithm that is invariant over small time scales raises some questions. How is the implementer to know if QUICv2 will allow the client first flight to have a consistent DCID but wildly varying SCIDs or UDP src ports? Or consistent SCID but randomized DCID?

I'll write up a section to discuss these concerns, but I think we should just write them down and shrug.

**Comment by nibanks** [comment]
Does the invariants ever state that the tuple can't change during the handshake? If that's allowed in the future, the first packet could be from one tuple with the client chosen CID, then the next could be from a new tuple, with the server chosen CID...

**Comment by martinduke** [comment]
It does not. If we feel strongly that something is likely to not remain constant in some future version of QUIC, we can recommend it that LBs not use it in their algorithm. If not, we should just note the assumption and move on.

**Comment by martinthomson** [comment]
There is a question here as to whether this is invariant, but here we go...

The goal is to route on the basis of connection ID as much as possible.  But you don't always have an existing mapping.  That might be because you don't know if the connection ID was generated locally, or because you know for certain that it wasn't.  In those cases, the only thing you have to fall back on is the addressing information.  So as Udip says, keeping a cache of flows for those packets you can't recognize is sensible.

In reading this, I was thinking "what can the invariants draft say about this?"  And it seems like there is something we could say here.

Right now, when you get a packet, there is some uncertainty about whether the destination connection ID is one of yours.  That is pretty much unavoidable for the long header, unless we create a new invariant way of signaling this (which I don't think we will do).  However, for the short header, I think we could say, definitively, that the connection ID is one that the destination server has selected.  That might help load balancers in this situation.  From my reading of this thread, it seems like this property was assumed throughout, but I realize that we never wrote that down.

**Comment by nibanks** [comment]
Ideally, we'd want the following promises from the Invariants:

- Short header packets always use your chosen CID
- Long header packets never change UDP 4-tuple
- Long header packets from the client have a constant source CID

**Comment by martinduke** [comment]
Only 1 client-chosen server CID per connection would be sufficient as well,
I think.

For packets that contain a client-chosen server CID, we need the LBs to
have something consistent to grab on to: this could be any combination of
UDP address/port
source CID
destination CID.

if any of these become invariant, we can tell LBs to use it exclusively
when handling non-compliant DCIDs.

**Comment by martinthomson** [comment]
> Only 1 client-chosen server CID per connection would be sufficient as well, I think.

This is on the basis that the load balancer can route based on the destination connection ID always.  I think that is right.  And it might be my preferred option.  The list of asks increases if you don't have that, as Nick points out.

**Comment by martinduke** [comment]
Martin, the PR has a pretty good list of relevant things that are not quite
guaranteed by the invariants draft. We don’t have to have them all but if
any are oversights please put them in.

**Comment by huitema** [comment]
In V1, we do assume that the addresses and ports will remain constant during the handshake. That means we can hash or route based the "non-compliant DCID" based on the combination of addresses, ports, SCID and DCID. This has an interesting robustness property: Initial packets sent by different parties will be routed to different contexts, even if the SCID and DCIDs collide -- either by mistake or intentionally. We may think of relaxing the rule in a future version and allow addresses to change during handshake, but I would not like losing the current robustness.
