### ISSUE TITLE
Inconsistent use of DCID and Server ID

### ISSUE THREAD

**Issue by enygren** [quicwg/load-balancers#201]
The current draft uses DCID half the time and Server ID the other half the time.
It should pick one and be consistent.  (It would also help to have some introduction
early on that explains the three components of the CID:  the first octet, the Server ID, and the nonce.)

**Comment by martinduke** [comment]
DCID and Server ID are different concepts!

The Destination Connection ID is the full connection ID addressed to the server.

The Server ID, as you state, is a part of that connection ID
