### ISSUE TITLE
Tweak non-compliant DCID recommendation

### ISSUE THREAD

**Issue by martinduke** [quicwg/load-balancers#22]
@martinthomson sayeth on the list:

>  That routing will rely on the stability of a subset of fields.  I would select from (source IP, source port, destination IP, destination port, DCID) and no others.

It would be useful to include something like this in Section 4 as a non-normative hint on what fields to use, since our hint currently consists of an example that just uses the DCID.

Similarly, make that assumption clearer in Section 8.

**Comment by DavidSchinazi** [comment]
For what it's worth, Google's load balancer only uses destination CIDs for routing. We always pick 64bit CIDs during the handshake so we can assume that short headers always carry 64bit CIDs.

**Comment by martinduke** [comment]
Do all CIDs resolve to a valid server ID?

**Comment by nibanks** [comment]
@DavidSchinazi do you not care about an attacker specifically crafting destination CIDs to attack a particular server?

**Comment by DavidSchinazi** [comment]
@martinduke 
> Do all CIDs resolve to a valid server ID?

We do not have a concept of server ID, but yes every CID routes to a server.

@nibanks
> @DavidSchinazi do you not care about an attacker specifically crafting destination CIDs to attack a particular server?

We do not care about that attack. I haven't seen any indication that it can actually cause harm in real life.

**Comment by martinduke** [comment]
@DavidSchinazi very well, then you have no non-compliant DCIDs. You would only need to upgrade your LBs for new versions if they allowed client-chosen DCIDs < 8 bytes.
