### ISSUE TITLE
Support of server generated HCID with retry tokens

### ISSUE THREAD

**Issue by huitema** [quicwg/load-balancers#34]
Since draft 28, the retry mechanism includes a requirement that the client DCID in the retried connection matches the server SCID in the retry packet. I do not see a discussion of mechanisms to verify the retried DCID in section 5 of the draft.

**Comment by martinduke** [comment]
I suggest you have a look at Sec 6 of the editor's draft:
https://quicwg.org/load-balancers/draft-ietf-quic-load-balancers.html#name-retry-service

**Comment by huitema** [comment]
Yes of course, this is addressed in the editor's draft. Let's close this issue.
