### ISSUE TITLE
Simplify the configuration by merging server-id and zero-pad

### ISSUE THREAD

**Issue by huitema** [quicwg/load-balancers#41]
The encrypted CID format includes a zero-pad field that is used to detect whether the decryption succeeded or not. I suggest merging this field with the server ID field, and test whether the decryption succeed by checking whether the server ID is valid or not. This assumes that the server ID field is sparsely populated. For example, if there are just 256 servers, in theory a 1-octed field would be sufficient; instead, we could use a 4 or 5 octet server ID field that would be sparsely populated, allowing for error detection.

This would allow for unified validity detection across all supported methods:
* clear text: verify that the server ID is valid;
* obfuscated: the divider need to have the same size as the full length server ID; the modulo is the server ID; validity can be verified there.
* stream: decrypt and verify that the server-id is valid
* encrypt: decrypt and verify that the server-id is valid

It would also allows for simplification of the configuration for the encrypted method, by specifying just one field instead of two.

**Comment by martinduke** [comment]
Yes, I agree this is simpler with no cost at all. Care to do a PR?
