### ISSUE TITLE
A little confused about configuration agent

### ISSUE THREAD

**Issue by william-zk** [quicwg/load-balancers#46]
Hi Author:
    I have a little confused about 'configuration agent', from the description of draft, I think it should be a centralized control plane of 'load balancer' and 'server', but from the name 'agent', it seems like it should be a agent component which was used to receive message from control plane. So, what is the most correct definition of 'configuration agent'?

**Comment by martinduke** [comment]
In the definitions section, it says: "A "configuration agent" is
the entity that determines the QUIC-LB configuration parameters for the network
and leverages some system to distribute that configuration."

The draft isn't really trying to define the architecture of the control plane. I'm not sure what the distinction is, for this spec, between being "the control plane" or something that "receives messages from the control plane". It is whatever is assigning server IDs.

Is there other language that would make this clearer?

**Comment by william-zk** [comment]
Um...I got it. My question comes from that we want to do an implementation about quic-lb, and contribute it to the nginx community, but for nginx, there are not any uniform centralized component to generate and distribute server ID, so we are confused with that if we should do a 'configuration agent' implementation. From your answer, we think that we can just open source quic-lb route ability, and provide a uniform server id usage api.

**Comment by martinduke** [comment]
Ah. So the draft originally had an in-band config channel but the group pulled it out for several reasons. I am personally not sure how people will deploy configurations for QUIC-LB in the real world, but for now you probably can't go wrong with adding the parameters to a configuration interface and just having a human being start the process.

I would suspect that open source QUIC servers would have a check box that says "accept QUIC-LB configuration" or something and then it would open a REST interface or whatever to accept it. I would love to hear from cloud providers to understand what config frameworks there are, but I suspect we're going to write something down in a draft somewhere.

**Comment by william-zk** [comment]
> I would suspect that open source QUIC servers would have a check box that says "accept QUIC-LB configuration" or something and then it would open a REST interface or whatever to accept it. I would love to hear from cloud providers to understand what config frameworks there are, but I suspect we're going to write something down in a draft somewhere.

Ah,  maybe a brief introduction can be write into `1.1.  Terminology`

**Comment by martinduke** [comment]
so this is already there:
Sec 1: 
While this document describes a small set of configuration parameters to make
the server mapping intelligible, the means of distributing these parameters
between load balancers, servers, and other trusted intermediaries is out of its
scope. There are numerous well-known infrastructures for distribution of
configuration.

Sec 1.1
A "configuration agent" is
the entity that determines the QUIC-LB configuration parameters for the network
and leverages some system to distribute that configuration.

Is this what you're looking for?

**Comment by william-zk** [comment]
> so this is already there:
> Sec 1:
> While this document describes a small set of configuration parameters to make
> the server mapping intelligible, the means of distributing these parameters
> between load balancers, servers, and other trusted intermediaries is out of its
> scope. There are numerous well-known infrastructures for distribution of
> configuration.
> 
> Sec 1.1
> A "configuration agent" is
> the entity that determines the QUIC-LB configuration parameters for the network
> and leverages some system to distribute that configuration.
> 
> Is this what you're looking for?

OK, thanks for answering, I'd close this issue soon
