### ISSUE TITLE
Cut obfuscated server ID algorithm

### ISSUE THREAD

**Issue by martinthomson** [quicwg/load-balancers#47]
As discussed at IETF 108.  Split from #8.

**Comment by martinduke** [comment]
Thanks for filing this. I agree that this was the feedback, but I'll take it from the list to be sure.

**Comment by ianswett** [comment]
Removing this seems fine to me.

**Comment by huitema** [comment]
Yes, do it.

**Comment by pravb** [comment]
Seems fine.

**Comment by janaiyengar** [comment]
Do it.

**Comment by DavidSchinazi** [comment]
Do it.

**Comment by martinduke** [comment]
Nick Harper concurred on the list
