### ISSUE TITLE
 A bit maybe used in cid  to mark whether the server info encoded in the long header or not?

### ISSUE THREAD

**Issue by Lingtaonju** [quicwg/load-balancers#50]
Dear sir,
As you know,  there is no bit in the cid to mark whether the cid encoded the server info or not.  In this case, no matter the server info encoded or not, the load balancer needs to  decrypt or decode the cid. Do you think this is a useless try when the packet is the first initial packet?  Do you think this is a useful idea to expand  the cid format to use the first bit to mark the cid encoded or not?   However, in this case, the client need to obey the rule.

**Comment by martinduke** [comment]
In fact, there is a bit. If the first two bits are '11' that means that the server didn't encode its ID and the load balancer should use 4-tuple routing:

https://quicwg.org/load-balancers/draft-ietf-quic-load-balancers.html#name-configuration-failover

The very first packet usually has a CID chosen by the client, which knows nothing about QUIC-LB. The beginning of Section 4 is mostly about how load balancers should handle these.

**Comment by Lingtaonju** [comment]
![image](https://user-images.githubusercontent.com/19946268/91683247-ac795800-eb86-11ea-924f-cdb889658871.png)
OK, I almost have forgot this first two Config Rotation bits can used to mark the cid server info's  validity.

However, in this case, I want to know , for the very first packet, will the draft  suggest  the clients to generate the dcid with the first two bits "11" , if they knows  the QUIC-LB used.
 
As,  if so,  the  QUIC-LB  know all packets' cid information to prevent useless decode/decrypt  try for the very first packet.

**Comment by Lingtaonju** [comment]
OK, I almost have forgot this first two Config Rotation bits can used to mark the cid server info's  validity.

However, in this case, I want to know , for the very first packet, will the draft  suggest  the clients to generate the dcid with the first two bits "11" , if they knows  the QUIC-LB used.
 
As,  if so,  the  QUIC-LB  know all packets' cid information to prevent useless decode/decrypt  try for the very first packet.

**Comment by martinduke** [comment]
No, this draft does not assume client cooperation at all. The very beginning of Section 4 explains how to handle client-generated CIDs.

**Comment by Lingtaonju** [comment]
> No, this draft does not assume client cooperation at all. The very beginning of Section 4 explains how to handle client-generated CIDs.

Thanks for your reply. Actually, I understand you works and Section 4.
However, my point is that , even this draft does not assume client cooperation at all,  this draft can suggest the client to generate a cid with 11  for the very first initial packet.

This is useful to QUIC-LB if client obeys the rule, if not , the Section 4 also works well.

**Comment by martinduke** [comment]
In #52 I'm adding CR bits as a reason for noncompliance.

It's fine if the client wants to set '11' , but I don't think it's important to do that. At most all we're saving the LB is a very small decrypt operation.

**Comment by Lingtaonju** [comment]
Even thought the decryption has a low consumption, I insist that the cost can be avoided.

I admit that the lb can't assume client cooperation at all, however, the draft can suggest the client to obey the rule: 
_" As, it is impossible for the client to know the server information at the beginning of the QUIC conn, so the DCID in the initial can't encode the server info, in this case,  the Client should make the first two bits with "11". "_
