### ISSUE TITLE
Any suggestion about transmit client ip from quic-lb to quic-server?

### ISSUE THREAD

**Issue by william-zk** [quicwg/load-balancers#51]
Dear author:
    As you know, in many production scenarios, quic-server need to know the real ip/port of client. But when there is a quic-lb in the middle(a fullnat quic-lb), there are not any standard way to implement this function. Actually this function is not difficult to implement, will quic-lb-draft suggest or define a standard way for this function later?

**Comment by martinduke** [comment]
That is not currently an objective for this document. I would probably start with taking the PROXY protocol and adapting it for UDP. Perhaps that would be a good draft!

**Comment by william-zk** [comment]
Ah, I got it

**Comment by william-zk** [comment]
Um...I reconsider the situation, can UDP-PROXY-protocol cover all UDP-based transport protocol? Consider this, for QUIC, we may send client ip to quic-server when receive initial packet. For RTP, we may send client ip to real-server when receive first packet...
There are so much UDP-based protocol, can all situation be covered in one draft?

**Comment by martinduke** [comment]
Yes

**Comment by william-zk** [comment]
👌 Looking forward to your draft, by the way, could you please tell me when will you start writing this draft?

**Comment by martinduke** [comment]
I'm not sure I volunteered to write it!

**Comment by william-zk** [comment]
> I'm not sure I volunteered to write it!

Ah, if you have any interests to do this, I would like to do some contribution about it

**Comment by william-zk** [comment]
Furthermore, I think it's a very important function for production environment

**Comment by Lingtaonju** [comment]
Is it possible that in quic lb, only a special proxy protocol is designed for quic, such as carrying pp packet only for initial packet, so as to avoid per-packet carrying to reduce overhead ?

**Comment by martinduke** [comment]
IMO Proxy Protocol is a NAT function, not a load balancing function. I don't think it belongs in this draft. I do have an individual draft (quic-natsupp) that touches on some issues with QUIC NATs, and this could house this work, but I think it'd be better just to write a draft that describes this.

I'll also note that the latest proxy protocol spec seems to offer UDP support, if I'm reading it correctly:  https://developers.cloudflare.com/spectrum/getting-started/proxy-protocol/#:~:text=When%20using%20UDP%20(currently%20an,Proxy%20Protocol%20to%20'on'.

There are some complexities in doing this well for QUIC. It ought to be version-independent (so no using specific long header packet types) and has to handle address migration properly.

**Comment by martinduke** [comment]
closing this as out of scope for quic-lb.
