### ISSUE TITLE
Keepalive design discussion

### ISSUE THREAD

**Issue by william-zk** [quicwg/load-balancers#53]
Hi author:
    Will quic-lb design Keepalive mechanism next? Surely it's a very important mechanism in load balancer.

**Comment by martinduke** [comment]
I'm not sure what you mean by a keepalive mechanism. Layer 4 load balancers can't inject messages into the connection. What are you trying to achieve?

**Comment by martinduke** [comment]
Any further response to this?

**Comment by william-zk** [comment]
Thanks for answering
