### ISSUE TITLE
question about timestamp in token

### ISSUE THREAD

**Issue by Lingtaonju** [quicwg/load-balancers#55]
As the draft describes:

'The date-time string is a total of 20 octets and encodes
 the time the token was generated. The format of date-time is
 described in Section 5.6 of [RFC3339].'

this needs 20 octets in ascii,
may be the unix time which is the the number of seconds since the Unix epoch in 8 octets
is a better choice in transmission and computing ?

**Comment by martinduke** [comment]
@Lingtaonju  have a look at the PR, please
