### ISSUE TITLE
SNI switching

### ISSUE THREAD

**Issue by martinduke** [quicwg/load-balancers#60]
Some load balancers today switch based on the SNI. Obviously, this is not version-invariant. We should add some language about this.

What should such an LB when it encounters an unknown version? It probably has no choice but to forward it based on CID and hope for the best.

**Comment by martinduke** [comment]
If the differing domains trust each other, the servers could helpfully generate Retry packets to redirect the client to the right place. This assumes a bunch of shared state, and that those servers support the same version while the LB does not.

Of course, if version support differs, the VN process has serious problems.

**Comment by william-zk** [comment]
Maybe encrypt sni will be the real standard later(see https://tools.ietf.org/html/draft-ietf-tls-esni-08), I just think that there is no need for quic lb routing by sni
