### ISSUE TITLE
SCID acronym

### ISSUE THREAD

**Issue by martinthomson** [quicwg/load-balancers#7]
This is often used to mean Source Connection ID in other contexts.  A collision here is likely to cause confusion.

**Comment by martinduke** [comment]
Recommended name? SCCID?

**Comment by nibanks** [comment]
I think it might just be best to call it the "Server CID" any other abbreviated term will get confused IMO.

**Comment by martinduke** [comment]
"Server CID" doesn't seem to fit will with "Stream Cipher Connection ID"

**Comment by nibanks** [comment]
So SCID didn't mean "Server Connection ID"? There is definitely confusion here. I'd just recommend not abbreviating anything more than CID.

**Comment by martinduke** [comment]
I guess this proves MT's point. "STream Cipher Connection ID" (just like PCID, OCID, BCID)

**Comment by martinduke** [comment]
Looking again, the document never uses any acronym for 'stream cipher connection ID', so there's no issue there. This is just about 'S' meaning "source" or "server".
