### ISSUE TITLE
Server ID: bits instead of octets?

### ISSUE THREAD

**Issue by martinduke** [quicwg/load-balancers#80]
@ianswett asks if there is added value in expressing server ID lengths in bits instead octets.

This is a bit of implementation complexity and a lot of churn in the spec and the handful of implementations that exist, but it does give the configuration agent a little more granularity.

Does anyone find the value of this granularity to be compelling?

**Comment by ianswett** [comment]
My thinking is that increasing/decreasing the server ID space by 256 is quite a large jump and could make config rotation a bit more complex.

Adding an extra bit to the server ID doubles the number of IDs, which is a fairly widely used increase in data structures and algorithms.

**Comment by martinduke** [comment]
While having such fine control would optimize for efficiency, splitting up bytes like this would complicate implementation. I'm also doubt that 1B of overhead is really going to affect anything.

Closing this issue due to old age; can reopen if anyone wants to fight it out.
