### ISSUE TITLE
Low-config PCID: why stop using some server IDs?

### ISSUE THREAD

**Issue by dtikhonov** [quicwg/load-balancers#81]
This part is unclear to me:

> A server SHOULD have a mechanism to stop using some server IDs if the list gets large relative to its share of the codepoint space, so that these allocations time out and are freed for reuse by servers that have recently joined the pool.

It is not obvious why these server IDs would be used by new server instances.

**Comment by martinduke** [comment]
Imagine a case where the entire server ID space has been allocated and these allocations never expire. Then there is no way for new pool members to receive assignments unless the config agent issues a whole new configuration! SIDs have to forward to their original assignments, or connections will break.

**Comment by dtikhonov** [comment]
I see!  Thank you for the explanation.
