### ISSUE TITLE
Low-Config CID creating huge problems with coexistence of configurations

### ISSUE THREAD

**Issue by martinduke** [quicwg/load-balancers#84]
For low-config CID (LCID), which dynamically allocates server IDs, the current editor's draft has a heuristic to extract a server ID from a client-generated non-compliant CID. The fundamental issue is that the server *has* to get an SID from an incoming Initial, even if the SR bits of the Connection ID imply that it doesn't map to the LCID config.

> 
> If the DCID references the 4-tuple routing bits or an undefined configuration, use the following procedure to establish a predictable template for server ID extraction:
> * Identify the instance of Low-Config CID configuration with the largest config rotation codepoint. For example, if configurations 0b10, 0b01, and 0b00 all use the low-config CID algorithm and have server ID lengths of 3, 5, and 7 octets, respectively, and a packet comes in with codepoint 0b11, the load balancer would extract 3 octets for the server ID.
> * Extract the appropriate number of octets.
> * If the server ID matches one already in the table, forward the packet to that server.
> * If not, the load balancer runs the algorithm of its choosing and adds the extracted server ID to the table corresponding to the highest-value Low-Config CID Configuration codepoint.

This doesn't work with config rotation. The main principle in CR is that the load balancer needs to get the configuration first -- otherwise the server might generate CIDs that the LB can't route, and we break ongoing connections. Given that, we have a problem. Consider:

1. LB and server both have LCID configuration 0b00 with SIDL of 1.
2. LB gets LCID configuration 0b01 with an SIDL of 2.
3. LB gets a packet with CR bits 0b01 and octets 2-3 0xfa13, and randomly forwards it to the server
4. The LB will add an SID entry for 0xfa13, but the server will add an SID entry for 0xfa.
5. The server will generate CIDs with CR 0xb00 and SID 0xfa, and the LB will not route them correctly.

Stated more generally: in the current design, the LB can never be sure if the server has a given configuration and that makes it very hard for the LB to infer what the server is going to do with a given CID to get an SID for its table. We don't even know if it's non-compliant at the server or not!

There are some potential fixes here:
1) Give up on dynamic server ID allocation
2) Have the LB keep track of config rotation bits it's observed in short header packets to each server -- this is an indication the server has the CR bits. This is also seems vulnerable to attack with injection of random short-header packets.
3) Reserve the SID corresponding to *all* configurations when routing a packet. In effect, this makes it impossible to adapt the crypto algorithms to use dynamically allocated server ID and have them coexist with plaintext ones: the crypto algorithms will essentially have randomly distributed plaintext fields, so the table will fill up fast.
4) Remove config rotation from dynamic allocation; this makes changes to config a site maintenance event. This also effectively prevents using crypto with dynamic allocation, because you can't rotate keys.
5) Change the behavior of a server when it gets CR bits it doesn't understand. Don't extract a server ID. If the server has no IDs because it just booted, simply echo the client-generated CID. When the server gets a config that lets it extract an SID from this, or gets a CID on another connection that it can decode, then it can update the CID on this connection. This implies that we could have valid short header packets with non-compliant DCIDs, so we'd have to have the LB admit these instead of dropping them like it does currently.
6) Same as #5, but instead of echoing the client-generated CID, it uses the 4-tuple routing bits for a new CID. This will make the
CID compliant, but abandon the whole purpose of QUIC-LB until an Initial with the right CR bits arrives (1 in 4 chance per connection).

***

Unfortunately, this breaks even more badly it coexists with a configuration with static SIDs. Another example:
1. LB and server have LCID config 0b00 with an SIDL of 1. Server A has SID 0x01 and Server B has SID 0x02.
2. LB gets stream CID config 0b01 (encrypted, static SIDs)
3. An Initial packet has CR bits 0b01. The second octet is 0x02 but the proper SCID decoding maps to Server A. So, it routes to Server A.
4. Server A doesn't have config 0b01 yet, so it extracts an SID from the CID and adds 0x02 to its list of SIDs. It generates an Low-config CID that the LB will route to Server B!

From this, I conclude that dynamically and statically configured SIDs can't safely coexist in the same config space.

***

This is all very hard to reason about. All the options are ugly but my instinct is to retreat to the first option and just abandon this dynamic design.

**Comment by huitema** [comment]
For the stateless algorithm, can we assume that servers are configured with a "current epoch" in a way that's properly synchronized with the LB, and that the epoch is encoded in the first byte of the "compliant" CID? Then the LB can do the following:

1) For Initial packets, assume non compliance. Treat CID as if they were part of the current epoch. Derive mapping from CID to server ID according to current epoch' key. 

2) For all other packets, assume compliance. If epoch is "too old", drop the packet (server should have sent new CID to client.) Otherwise, derive mapping from CID to server ID according to specified epoch' key. (Or if CID in cache, use cache.)

**Comment by martinduke** [comment]
Thanks Christian!

I am not sure I fully understand your proposal, but I will make some points:

1) quic-lb tries to distinguish only short-header and long-header packets to remain version invariant. There is no notion of Initials.

2) the second Initial carries a server generated CID, and 0RTT does not. so it is not so simple as sniffing the Initial codepoint.

3) IIUC the CR codepoint is much like your "epoch." I think the problem is when you are switching epochs; the LB must understand both and can't be sure which epoch any given server is on. Indeed, this is the heart of the issue.

Or perhaps I've wildly misunderstood your proposal.

**Comment by huitema** [comment]
So it boils down to a synchronization problem. The LB knows that a server is in epoch N+1 if it sees a CID from that server with the new epoch. So the transition will work like this:

1) Before transition, server use epoch N. LB sees from that server CID with epoch N.
2) At some point, LBtransitions to N+1.
3) If the server notices the LB's transition, it also moves to epoch N+1
4) Some time after that, the LB sees clients sending packets to that server with DCID marked for epoch N+1, at which points it knows server and LB are synchronized.

The main problem is that there is no synchronization signal from LB to server. The server cannot look at the ID and infer that the LB has moved to a new epoch.

It might be possible to use the stateless Reset to solve that. When it receives a new initial that would map to server X before confirmation that server X is on epoch N+1, the LB might send a stateless reset to the client, suggesting a conforming DCID marked with epoch N+1. The server will receive the retried Initial, and learn that the new epoch has started. The idea probably needs some exploring, but that seems plausible.

**Comment by martinduke** [comment]
Assuming handshakes are going on, yes, LBs can see what configs are operating. This is my option 2 but using egress SCID instead of ingress DCID, definitely an improvement.

Several drafts ago we moved away from explicit in-band signaling. Now we're headed back.

**Comment by martinduke** [comment]
@ianswett and I had a long discussion about this problem. We reached a consensus that solution #6 was the least bad one. To summarize:
1. If a client-generated CID comes in that does not match a known config, do not add an SID entry at the LB or server.
2. If it does match a config codepoint, extract the SID accordingly and add it to the table.
3. There will be cases where the LB has a config codepoint, but the server does not. If so, the LB has "wasted" an entry but this is not a big problem. The reverse would be a problem, but it is already a requirement for the LB to have the superset of server configs.
4. When it first loads a config, the server will not have any SIDs. This should correct itself after a handful of connections, but until it does the CIDs it generates use the 4-tuple routing codepoint. When it does get an SID, it can retire the old ones across all connections. Thus, there are transitory states where a server can't support rebinding and migration.

This is still open for discussion, but I am working on a large PR to reorganize the whole routing section around dynamic SID allocation.

**Comment by ianswett** [comment]
One Note: I believe it can support NAT rebinding, just not migration or changing CIDs.  If a client unknowingly changes its address due to a NAT rebind, it does not change its CID.

**Comment by martinduke** [comment]
No, because if it's the 4-tuple routing codepoint the LB ignores the rest of the CID. So it will route based on the (changed) 4tuple

**Comment by ianswett** [comment]
Of course, I was thinking of something else.
