### ISSUE TITLE
Consider an alternative name to 'non-compliant'

### ISSUE THREAD

**Issue by ianswett** [quicwg/load-balancers#98]
In PR #95 I suggested non-routable, though I realize non-conformant may also be an option.

The sentence which caused me to suggest non-routable is: https://github.com/quicwg/load-balancers/blob/master/draft-ietf-quic-load-balancers.md#non-compliant-connection-ids-non-compliant

> These client-generated CIDs might not conform to the expectations of the routing algorithm and therefore not be routable by the load balancer. Those that are not routable are "non-compliant DCIDs" and receive similar treatment regardless of why they're non-compliant:

I'm happy to write a PR if others find non-compliant potentially confusing as well.

**Comment by martinduke** [comment]
I like it. Let's go with it.
