### ISSUE TITLE
Consider an alternative name to 'arbitrary' algorithm

### ISSUE THREAD

**Issue by ianswett** [quicwg/load-balancers#99]
I'd suggest 'Fallback' or another word than arbitrary.

A definition of Arbitrary is: "Based on random choice or personal whim, rather than any reason or system."

In fact, there are sensible constraints on this algorithm to ensure routing works correctly for non-compliant CIDs and connections don't fail.

**Comment by martinduke** [comment]
Agreed.

**Comment by martinduke** [comment]
Closed by #109
